### ISSUE TITLE
Some packages in mol.yml are incorrect, such as cudatoolkit, geometric, scatter, etc

### ISSUE THREAD

**Issue by Lumen97** [Layne-Huang/PMDM#13]
Below is a Conda environment that can run PMDM correctly:

```
name: pmdm
channels:
  - nvidia
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - acpype=2022.7.21=pyhd8ed1ab_1
  - ambertools=22.4=py39h804d063_0
  - arpack=3.7.0=hdefa2d7_2
  - blas=1.0=mkl
  - boost=1.78.0=py39hda80f44_5
  - boost-cpp=1.78.0=h2c5509c_4
  - bottleneck=1.3.7=py39ha9d4c09_0
  - brotli=1.0.9=h5eee18b_7
  - brotli-bin=1.0.9=h5eee18b_7
  - brotli-python=1.0.9=py39h6a678d5_7
  - bzip2=1.0.8=hd590300_5
  - c-ares=1.19.1=h5eee18b_0
  - ca-certificates=2024.3.11=h06a4308_0
  - cairo=1.18.0=h3faef2a_0
  - certifi=2024.2.2=py39h06a4308_0
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - contourpy=1.2.0=py39hdb19cb5_0
  - cuda-cudart=11.8.89=0
  - cuda-cupti=11.8.87=0
  - cuda-libraries=11.8.0=0
  - cuda-nvrtc=11.8.89=0
  - cuda-nvtx=11.8.86=0
  - cuda-runtime=11.8.0=0
  - cuda-version=11.8=h70ddcb2_3
  - cudatoolkit=11.8.0=h4ba93d1_13
  - cudatoolkit-dev=11.7.0=h1de0b5d_6
  - cudnn=8.9.7.29=hbc23b4c_3
  - curl=8.5.0=hdbd6064_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - cython=3.0.10=py39h5eee18b_0
  - expat=2.5.0=h6a678d5_0
  - ffmpeg=4.3=hf484d3e_0
  - fftw=3.3.10=nompi_hc118613_108
  - filelock=3.13.1=py39h06a4308_0
  - font-ttf-dejavu-sans-mono=2.37=hd3eb1b0_0
  - font-ttf-inconsolata=2.001=hcb22688_0
  - font-ttf-source-code-pro=2.030=hd3eb1b0_0
  - font-ttf-ubuntu=0.83=h8b1ccd4_0
  - fontconfig=2.14.2=h14ed4e7_0
  - fonts-anaconda=1=h8fa9717_0
  - fonts-conda-ecosystem=1=hd3eb1b0_0
  - freetype=2.12.1=h4a9f257_0
  - gdbm=1.18=hd4cb3f1_4
  - glib=2.78.4=h6a678d5_0
  - glib-tools=2.78.4=h6a678d5_0
  - gmp=6.2.1=h295c915_3
  - gmpy2=2.1.2=py39heeb90bb_0
  - gnutls=3.6.15=he1e5248_0
  - greenlet=3.0.1=py39h6a678d5_0
  - hdf4=4.2.15=h9772cbc_5
  - hdf5=1.12.2=nompi_h4df4325_101
  - icu=73.2=h59595ed_0
  - idna=3.4=py39h06a4308_0
  - importlib_resources=6.1.1=py39h06a4308_1
  - intel-openmp=2023.1.0=hdb19cb5_46306
  - jinja2=3.1.3=py39h06a4308_0
  - jpeg=9e=h5eee18b_1
  - kiwisolver=1.4.4=py39h6a678d5_0
  - krb5=1.20.1=h143b758_1
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=3.0=h295c915_0
  - libaec=1.1.3=h59595ed_0
  - libblas=3.9.0=1_h86c2bf4_netlib
  - libbrotlicommon=1.0.9=h5eee18b_7
  - libbrotlidec=1.0.9=h5eee18b_7
  - libbrotlienc=1.0.9=h5eee18b_7
  - libcublas=11.11.3.6=0
  - libcufft=10.9.0.58=0
  - libcufile=1.9.1.3=0
  - libcurand=10.3.5.147=0
  - libcurl=8.5.0=h251f7ec_0
  - libcusolver=11.4.1.48=0
  - libcusparse=11.7.5.86=0
  - libdeflate=1.17=h5eee18b_1
  - libedit=3.1.20230828=h5eee18b_0
  - libev=4.33=h7f8727e_1
  - libffi=3.4.4=h6a678d5_0
  - libgcc-ng=13.2.0=h807b86a_5
  - libgfortran-ng=13.2.0=h69a702a_5
  - libgfortran5=13.2.0=ha4646dd_5
  - libglib=2.78.4=hdc74915_0
  - libgomp=13.2.0=h807b86a_5
  - libiconv=1.17=hd590300_2
  - libidn2=2.3.4=h5eee18b_0
  - libjpeg-turbo=2.0.0=h9bf148f_0
  - liblapack=3.9.0=5_h92ddd45_netlib
  - libnetcdf=4.9.1=nompi_h34a3ff0_101
  - libnghttp2=1.57.0=h2d74bed_0
  - libnpp=11.8.0.86=0
  - libnsl=2.0.1=hd590300_0
  - libnvjpeg=11.9.0.86=0
  - libpng=1.6.39=h5eee18b_0
  - libsqlite=3.45.2=h2797004_0
  - libssh2=1.10.0=hdbd6064_2
  - libstdcxx-ng=13.2.0=h7e041cc_5
  - libtasn1=4.19.0=h5eee18b_0
  - libtiff=4.5.1=h6a678d5_0
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=2.38.1=h0b41bf4_0
  - libwebp-base=1.3.2=h5eee18b_0
  - libxcb=1.15=h7f8727e_0
  - libxcrypt=4.4.36=hd590300_1
  - libxml2=2.12.6=h232c23b_1
  - libzip=1.10.1=h2629f0a_3
  - libzlib=1.2.13=hd590300_5
  - llvm-openmp=14.0.6=h9e868ea_0
  - lz4-c=1.9.4=h6a678d5_0
  - markupsafe=2.1.3=py39h5eee18b_0
  - mkl=2023.1.0=h213fc3f_46344
  - mkl-service=2.4.0=py39h5eee18b_1
  - mkl_fft=1.3.8=py39h5eee18b_0
  - mkl_random=1.2.4=py39hdb19cb5_0
  - mpc=1.1.0=h10f8cd9_1
  - mpfr=4.0.2=hb69a4c5_1
  - mpmath=1.3.0=py39h06a4308_0
  - munkres=1.1.4=py_0
  - ncurses=6.4=h6a678d5_0
  - netcdf-fortran=4.6.0=nompi_heb5813c_103
  - nettle=3.7.3=hbbd107a_1
  - networkx=3.1=py39h06a4308_0
  - numexpr=2.8.7=py39h85018f9_0
  - numpy=1.23.5=py39hf6e8229_1
  - numpy-base=1.23.5=py39h060ed82_1
  - openbabel=3.1.1=py39h2d01fe1_9
  - openh264=2.1.1=h4ff587b_0
  - openjpeg=2.4.0=h3ad879b_0
  - openssl=3.2.1=hd590300_1
  - packaging=23.2=py39h06a4308_0
  - packmol=20.010=h86c2bf4_0
  - pandas=2.1.3=py39hddac248_0
  - parmed=3.4.4=py39h227be39_0
  - pcre2=10.42=hebb0a14_0
  - perl=5.34.0=h5eee18b_2
  - pillow=10.2.0=py39h5eee18b_0
  - pip=23.3.1=py39h06a4308_0
  - pixman=0.43.2=h59595ed_0
  - pycairo=1.23.0=py39hd1222b9_0
  - pyparsing=3.0.9=py39h06a4308_0
  - pysocks=1.7.1=py39h06a4308_0
  - python=3.9.18=h0755675_1_cpython
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python-tzdata=2023.3=pyhd3eb1b0_0
  - python_abi=3.9=4_cp39
  - pytorch=2.1.1=py3.9_cuda11.8_cudnn8.7.0_0
  - pytorch-cuda=11.8=h7e8668a_5
  - pytorch-mutex=1.0=cuda
  - pytz=2023.3.post1=py39h06a4308_0
  - pyyaml=6.0.1=py39h5eee18b_0
  - rdkit=2022.09.1=py39hb00a813_2
  - readline=8.2=h5eee18b_0
  - reportlab=3.5.67=py39hfdd840d_1
  - requests=2.31.0=py39h06a4308_1
  - scipy=1.12.0=py39h5f9d8c6_0
  - setuptools=68.2.2=py39h06a4308_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlalchemy=2.0.25=py39h5eee18b_0
  - sqlite=3.41.2=h5eee18b_0
  - sympy=1.12=py39h06a4308_0
  - tbb=2021.8.0=hdb19cb5_0
  - tk=8.6.13=noxft_h4845f30_101
  - torchaudio=2.1.1=py39_cu118
  - torchtriton=2.1.0=py39
  - torchvision=0.16.1=py39_cu118
  - typing-extensions=4.9.0=py39h06a4308_1
  - typing_extensions=4.9.0=py39h06a4308_1
  - tzdata=2024a=h04d1e81_0
  - urllib3=2.1.0=py39h06a4308_1
  - wheel=0.41.2=py39h06a4308_0
  - xorg-kbproto=1.0.7=h7f98852_1002
  - xorg-libice=1.1.1=hd590300_0
  - xorg-libsm=1.2.4=h7391055_0
  - xorg-libx11=1.8.9=h8ee46fc_0
  - xorg-libxext=1.3.4=h0b41bf4_2
  - xorg-libxrender=0.9.11=hd590300_0
  - xorg-libxt=1.3.0=hd590300_1
  - xorg-renderproto=0.11.1=h7f98852_1002
  - xorg-xextproto=7.3.0=h0b41bf4_1003
  - xorg-xproto=7.0.31=h27cfd23_1007
  - xz=5.4.6=h5eee18b_0
  - yaml=0.2.5=h7b6447c_0
  - zipp=3.17.0=py39h06a4308_0
  - zlib=1.2.13=hd590300_5
  - zstd=1.5.5=hc292b87_0
  - pip:
      - aiohttp==3.9.4
      - aiosignal==1.3.1
      - amberlite==22.0
      - amberutils==21.0
      - async-timeout==4.0.3
      - attrs==23.2.0
      - biopython==1.83
      - easydict==1.13
      - einops==0.7.0
      - fonttools==4.45.0
      - frozenlist==1.4.1
      - fsspec==2024.3.1
      - joblib==1.4.0
      - lmdb==1.4.1
      - matplotlib==3.8.2
      - mmpbsa-py==16.0
      - multidict==6.0.5
      - packmol-memgen==1.2.3rc0
      - pdb4amber==22.0
      - psutil==5.9.8
      - pytraj==2.0.6
      - sander==22.0
      - scikit-learn==1.4.2
      - threadpoolctl==3.4.0
      - torch-cluster==1.6.3+pt21cu118
      - torch-geometric==2.4.0
      - torch-scatter==2.1.2+pt21cu118
      - torch-sparse==0.6.18+pt21cu118
      - torch-spline-conv==1.2.2+pt21cu118
      - tqdm==4.66.2
      - yarl==1.9.4
prefix: /home/user/miniconda3/envs/pmdm
```

**Comment by Layne-Huang** [comment]
Great thanks for this useful information. Yes, PMDM could work on this env. I will update the env file.

**Comment by lvjiayun** [comment]
I configured the environment according to the mol.yml file you provided and encountered the following issues:

Executing transaction: - By downloading and using the CUDA Toolkit conda packages, you accept the terms and conditions of the CUDA End User License Agreement (EULA): https://docs.nvidia.com/cuda/eula/index.html

| By downloading and using the cuDNN conda packages, you accept the terms and conditions of the NVIDIA cuDNN EULA -
  https://docs.nvidia.com/deeplearning/cudnn/sla/index.html

done
ERROR conda.core.link:_execute(699): An error occurred while installing package 'conda-forge::cudatoolkit-dev-11.7.0-h1de0b5d_6'.
Rolling back transaction: done

LinkError: post-link script failed for package conda-forge::cudatoolkit-dev-11.7.0-h1de0b5d_6
location of failed script: /mnt/home/ljy/anaconda3/envs/mol/bin/.cudatoolkit-dev-post-link.sh
==> script messages <==
<None>
==> script output <==
stdout: Running Post installation
downloading https://developer.download.nvidia.com/compute/cuda/11.7.0/local_installers/cuda_11.7.0_515.43.04_linux.run to /mnt/home/ljy/anaconda3/envs/mol/pkgs/cudatoolkit-dev/cuda_11.7.0_515.43.04_linux.run

stderr: Traceback (most recent call last):
  File "/mnt/home/ljy/anaconda3/envs/mol/bin/cudatoolkit-dev-post-install.py", line 311, in <module>
    _main()
  File "/mnt/home/ljy/anaconda3/envs/mol/bin/cudatoolkit-dev-post-install.py", line 304, in _main
    extractor.download_blobs()
  File "/mnt/home/ljy/anaconda3/envs/mol/bin/cudatoolkit-dev-post-install.py", line 91, in download_blobs
    self.download(dl_url, dl_path)
  File "/mnt/home/ljy/anaconda3/envs/mol/bin/cudatoolkit-dev-post-install.py", line 78, in download
    raise exc
  File "/mnt/home/ljy/anaconda3/envs/mol/bin/cudatoolkit-dev-post-install.py", line 76, in download
    subprocess.check_call(cmd)
  File "/mnt/home/ljy/anaconda3/envs/mol/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['wget', 'https://developer.download.nvidia.com/compute/cuda/11.7.0/local_installers/cuda_11.7.0_515.43.04_linux.run', '-O', '/mnt/home/ljy/anaconda3/envs/mol/pkgs/cudatoolkit-dev/cuda_11.7.0_515.43.04_linux.run', '-q']' returned non-zero exit status 4.

return code: 1

()
