### ISSUE TITLE
Unexpected Results in Sampling for Custom Pockets

### ISSUE THREAD

**Issue by nickyoungforu** [Layne-Huang/PMDM#21]
I generate molecules using the following command: 
python -u sample_for_pdb.py --ckpt checkpoints/500.pt --pdb_path test_data/3ug2.pdb --num_atom 50 --num_samples 2 --sampling_type generalized --build_method build
Why are the generated molecules all unstable ?

generated smile: [C].[C].[C].[C].[C].[C].[C].[C].[C].[C].[C].[C].[C].[C].[C].[C].[C].[C].[C].[C].[C].[C].[C].[C].[C].[C].[C].[C].[C].[C].[C].[C].[C].[C].[C].[C].[C].[C].[C].[C].[C].[C]#[C].[C][C]([C])[C][C][O].[O]
generated smile: [C].[C].[C].[C].[C].[C].[C].[C].[C].[C].[C].[C].[C].[C].[C].[C].[C].[C].[C].[C].[C].[C].[C].[C].[C].[C].[C].[C].[C].[C].[C].[C].[C].[C].[C].[C].[C].[C].[C].[C].[C].[C].[C].[C].[C]#[C].[N].[N].[O][O]
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:36<00:00, 36.71s/it]
[2024-05-06 16:16:47,651::test::INFO] valid:2
[2024-05-06 16:16:47,651::test::INFO] stable:0

**Comment by Layne-Huang** [comment]
Hi, most of the molecules in the training set are no more than 30 atoms. Therefore, it is hard for the pretrained model to generate a large molecule. Please decrease the argument "num_atom" to no more than 30 atoms.

**Comment by Layne-Huang** [comment]
Hi, PMDM could generate valid molecules for this target in my experiments. You could  increase the value of 'num_samples' to allow the model for more attempts.
<img width="825" alt="image" src="https://github.com/Layne-Huang/PMDM/assets/34830172/5d62286d-37e7-4006-ad8a-a6ad0b9d20e8">

**Comment by Tianjl9** [comment]
Thank you for your answer, but I encountered another problem. This is my command line：python -u PMDM_main/sample_for_pdb.py --ckpt /wuqi/stu/tianjl/PMDM/500.pt --pdb_path PMDM_main/my/3hmm/3hmmcut20/3hmmcut20_pocket.pdb --num_atom 35 --num_samples 10000 --sampling_type generalized
This is the error output：Traceback (most recent call last):
  File "/wuqi/stu/tianjl/PMDM/PMDM_main/sample_for_pdb.py", line 393, in <module>
    gmol = reconstruct_from_generated(pos, new_element, indicators)
  File "/wuqi/stu/tianjl/PMDM/PMDM_main/utils/reconstruct.py", line 521, in reconstruct_from_generated
    rd_mol = postprocess_rd_mol_1(rd_mol)
  File "/wuqi/stu/tianjl/PMDM/PMDM_main/utils/reconstruct.py", line 416, in postprocess_rd_mol_1
    atom.SetNumRadicalElectrons(num_radical)
OverflowError: can't convert negative value to unsigned int
how can i solve this problem？ @Layne-Huang

**Comment by Kartinaa** [comment]
> Thank you for your answer, but I encountered another problem. This is my command line：python -u PMDM_main/sample_for_pdb.py --ckpt /wuqi/stu/tianjl/PMDM/500.pt --pdb_path PMDM_main/my/3hmm/3hmmcut20/3hmmcut20_pocket.pdb --num_atom 35 --num_samples 10000 --sampling_type generalized This is the error output：Traceback (most recent call last): File "/wuqi/stu/tianjl/PMDM/PMDM_main/sample_for_pdb.py", line 393, in gmol = reconstruct_from_generated(pos, new_element, indicators) File "/wuqi/stu/tianjl/PMDM/PMDM_main/utils/reconstruct.py", line 521, in reconstruct_from_generated rd_mol = postprocess_rd_mol_1(rd_mol) File "/wuqi/stu/tianjl/PMDM/PMDM_main/utils/reconstruct.py", line 416, in postprocess_rd_mol_1 atom.SetNumRadicalElectrons(num_radical) OverflowError: can't convert negative value to unsigned int how can i solve this problem？ @Layne-Huang

I have same question here, looking forward to explaination.
