### ISSUE TITLE
generate novel molecules from a seed fragment using sample_frag.py

### ISSUE THREAD

**Issue by wenchangzhou-qtx** [Layne-Huang/PMDM#8]
Hey @Layne-Huang,

Is there a example mole file for generating novel molecules from a seed fragment? I'm using `sample_frag.py` with command `python -u sample_frag.py --ckpt data/500.pt --pdb_path receptor.pdb --mol_file frag.sdf --keep_index 1 --num_atom 20 --num_samples 10 --sampling_type generalized`

Also what do I put after the `--keep_index` option? Do you also have an example command line working for a real world case?

Thanks!

**Comment by Layne-Huang** [comment]
The keep index is the index of the seed fragment.

You could utilize the following code to visualize the index and decide which fragment you want to keep.
`from rdkit import Chem
mol = Chem.SDMolSupplier(f)[0]
smiles = Chem.MolToSmiles(mol)
print(smiles)
mol.RemoveAllConformers()
for i, atom in enumerate(mol.GetAtoms()):
    atom.SetProp('molAtomMapNumber', str(i+1))
# smiles = Chem.MolToSmiles(mol)
# print(smiles)
# mol = Chem.MolFromSmiles(smiles)
Draw.MolToImage(mol, size=(1000,1000))`
For example, you could set keep index as [1,2,7,8,18,19] for the following molecule.
![image](https://github.com/Layne-Huang/PMDM/assets/34830172/199b7baf-06dd-4514-b5b3-64b0ec3ba16b)

**Comment by wenchangzhou-qtx** [comment]
Hey @Layne-Huang,

Thanks for providing the above example, I'm able to index the molecule and tried to keep about 8 atoms as the initial seed fragment, but once I run it I got this error:
```
Traceback (most recent call last):
  File "~/softwares/PMDM/sample_frag.py", line 255, in <module>
    keep_index = torch.tensor(args.keep_index)
ValueError: too many dimensions 'str'

```
I tried this `python -u sample_frag.py --ckpt data/500.pt --pdb_path receptor.pdb --mol_file SD.frag.sdf --keep_index [1,2,3,4,5,6,7,8] --num_atom 20 --num_samples 100 --sampling_type generalized`

**Comment by Layne-Huang** [comment]
Please use the updated `sample_frag.py` file and use the command`python -u sample_frag.py --ckpt data/500.pt --pdb_path receptor.pdb --mol_file SD.frag.sdf --keep_index 1 2 3 4 5 6 7 8 --num_atom 20 --num_samples 100 --sampling_type generalized`.

Thank you.

**Comment by wenchangzhou-qtx** [comment]
Hey @Layne-Huang,

Thanks for updating the script. I just did a test but failed with the following messages:
```
Entropy of n_nodes: H[N] -1.3862943649291992
[2024-04-04 21:51:51,894::test::INFO] Namespace(pdb_path='receptor.4amber.pdb', mol_file='SD.frag.sdf', num_atom=20, keep_index=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 13, 14, 16, 17, 18, 19, 20, 21, 22, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35], build_method='build', cuda=False, savedir='test.pkl', ckpt='data/500.pt', save_traj=False, resume=None, tag='', out_dir=None, num_samples=10, batch_size=100, clip=1000.0, seed=3047, n_steps=1000, global_start_sigma=inf, local_start_sigma=inf, w_global_pos=1.0, w_local_pos=1.0, w_global_node=1.0, w_local_node=1.0, sampling_type='generalized', eta=1.0)
[2024-04-04 21:51:51,894::test::INFO] {'model': {'type': 'diffusion', 'network': 'MDM_full_pocket_coor_shared', 'hidden_dim': 128, 'protein_hidden_dim': 128, 'num_convs': 3, 'num_convs_local': 3, 'protein_num_convs': 2, 'cutoff': 3.0, 'g_cutoff': 6.0, 'encoder_cutoff': 6.0, 'time_emb': True, 'atom_num_emb': False, 'mlp_act': 'relu', 'beta_schedule': 'sigmoid', 'beta_start': 1e-07, 'beta_end': 0.002, 'num_diffusion_timesteps': 1000, 'edge_order': 3, 'edge_encoder': 'mlp', 'smooth_conv': False, 'num_layer': 9, 'feats_dim': 5, 'soft_edge': True, 'norm_coors': True, 'm_dim': 128, 'context': 'None', 'vae_context': False, 'num_atom': 10, 'protein_feature_dim': 31}, 'train': {'seed': 2021, 'batch_size': 16, 'val_freq': 250, 'max_iters': 500, 'max_grad_norm': 10.0, 'num_workers': 4, 'anneal_power': 2.0, 'optimizer': {'type': 'adam', 'lr': 0.001, 'weight_decay': 0.0, 'beta1': 0.95, 'beta2': 0.999}, 'scheduler': {'type': 'plateau', 'factor': 0.6, 'patience': 10, 'min_lr': 1e-06}, 'transform': {'mask': {'type': 'mixed', 'min_ratio': 0.0, 'max_ratio': 1.2, 'min_num_masked': 1, 'min_num_unmasked': 0, 'p_random': 0.5, 'p_bfs': 0.25, 'p_invbfs': 0.25}, 'contrastive': {'num_real': 50, 'num_fake': 50, 'pos_real_std': 0.05, 'pos_fake_std': 2.0}}}, 'dataset': {'name': 'crossdock', 'type': 'pl', 'path': './data/crossdocked_pocket10', 'split': './data/split_by_name.pt'}}
[2024-04-04 21:51:51,894::test::INFO] Loading crossdock data...
Entropy of n_nodes: H[N] -3.543935775756836
[2024-04-04 21:51:51,895::test::INFO] Loading data...
[2024-04-04 21:51:51,939::test::INFO] Building model...
[2024-04-04 21:51:51,939::test::INFO] MDM_full_pocket_coor_shared
{'type': 'diffusion', 'network': 'MDM_full_pocket_coor_shared', 'hidden_dim': 128, 'protein_hidden_dim': 128, 'num_convs': 3, 'num_convs_local': 3, 'protein_num_convs': 2, 'cutoff': 3.0, 'g_cutoff': 6.0, 'encoder_cutoff': 6.0, 'time_emb': True, 'atom_num_emb': False, 'mlp_act': 'relu', 'beta_schedule': 'sigmoid', 'beta_start': 1e-07, 'beta_end': 0.002, 'num_diffusion_timesteps': 1000, 'edge_order': 3, 'edge_encoder': 'mlp', 'smooth_conv': False, 'num_layer': 9, 'feats_dim': 5, 'soft_edge': True, 'norm_coors': True, 'm_dim': 128, 'context': 'None', 'vae_context': False, 'num_atom': 10, 'protein_feature_dim': 31}
sdf idr: wo_semantic/test
Entropy of n_nodes: H[N] -1.3862943649291992
linker atom number: 31
  0%|                                                                                       | 0/1 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "~/softwares/PMDM/sample_frag.py", line 266, in <module>
    data_list,_ = construct_dataset_pocket(num_samples*1,batch_size,dataset_info,num_points,num_points,start_linker,None,
  File "~/softwares/PMDM/utils/sample.py", line 154, in construct_dataset_pocket
    atom_type_linker = torch.cat([start_linker['linker_atom_type'], atom_type])
RuntimeError: Sizes of tensors must match except in dimension 0. Expected size 10 but got size 8 for tensor number 1 in the list.

```

Is it something strange about my ligand file? Here I have a fragment and I like to keep 31 atoms out of 35 in total.

**Comment by Layne-Huang** [comment]
Thanks for your feedback. There is some version error of the dataset_info in this file. I have uploaded the newest file. Please check it. Thank you!

**Comment by wenchangzhou-qtx** [comment]
Hey @Layne-Huang,

Sorry there is one more error after I tried the new version, it can run but failed with "RuntimeError: Not compiled with CUDA support", details are below

```
Entropy of n_nodes: H[N] -1.3862943649291992
linker atom number: 31
^M  0%|          | 0/1 [00:00<?, ?it/s]^M100%|██████████| 1/1 [00:00<00:00, 12.61it/s]
^M  0%|          | 0/1 [00:00<?, ?it/s]^M  0%|          | 0/1 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/hpc/users/wenchangzhou/softwares/PMDM/sample_frag.py", line 272, in <module>
    pos_gen, pos_gen_traj, atom_type, atom_traj = model.inpainting_sample(
  File "/hpc/users/wenchangzhou/softwares/PMDM/models/epsnet/MDM_pocket_coor_shared.py", line 979, in inpainting_sample
    protein_ctx = self.protein_encoder(
  File "~/softwares/mambaforge3/envs/pmdm/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "~/softwares/mambaforge3/envs/pmdm/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "~/softwares/PMDM/models/encoders/schnet.py", line 92, in forward
    edge_index = radius_graph(pos, self.cutoff, batch=batch, loop=False)
  File "~/softwares/mambaforge3/envs/pmdm/lib/python3.9/site-packages/torch_geometric/nn/pool/__init__.py", line 277, in radius_graph
    return torch_cluster.radius_graph(x, r, batch, loop, max_num_neighbors,
  File "~/softwares/mambaforge3/envs/pmdm/lib/python3.9/site-packages/torch_cluster/radius.py", line 135, in radius_graph
    edge_index = radius(x, x, r, batch, batch,
  File "~/softwares/mambaforge3/envs/pmdm/lib/python3.9/site-packages/torch_cluster/radius.py", line 82, in radius
    return torch.ops.torch_cluster.radius(x, y, ptr_x, ptr_y, r,
  File "~/softwares/mambaforge3/envs/pmdm/lib/python3.9/site-packages/torch/_ops.py", line 755, in __call__
    return self._op(*args, **(kwargs or {}))
RuntimeError: Not compiled with CUDA support

```

**Comment by Layne-Huang** [comment]
It is caused by the incompatibility of the **CUDA** version and **pytorch geometric** package and its relative packages including **torch_scatter**, **torch_clutser** and **torch_sparse**.

**Comment by wenchangzhou-qtx** [comment]
Hey @Layne-Huang,

Can you see any of them are incompatible? My environment has:
```
torch                     2.2.1                    pypi_0    pypi
torch-cluster             1.6.3                    pypi_0    pypi
torch-geometric           2.4.0                    pypi_0    pypi
torch-scatter             2.1.2                    pypi_0    pypi
torch-sparse              0.6.18                   pypi_0    pypi
torchaudio                2.2.1                    pypi_0    pypi
torchvision               0.17.1                   pypi_0    pypi
```
I have cuda 11.8, here is the output of `nvcc --version`
```
nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2022 NVIDIA Corporation
Built on Wed_Sep_21_10:33:58_PDT_2022
Cuda compilation tools, release 11.8, V11.8.89
Build cuda_11.8.r11.8/compiler.31833905_0
```

**Comment by Layne-Huang** [comment]
Please use this link: [https://data.pyg.org/whl/](url)

**Comment by wenchangzhou-qtx** [comment]
Thanks! @Layne-Huang 

I believe I now have them all compatible, there is still error as below
```
Traceback (most recent call last):
  File "~/softwares/PMDM/sample_frag.py", line 272, in <module>
    pos_gen, pos_gen_traj, atom_type, atom_traj = model.inpainting_sample(
  File "~/softwares/PMDM/models/epsnet/MDM_pocket_coor_shared.py", line 1028, in inpainting_sample
    net_out = self.net(
  File "~/softwares/PMDM/models/epsnet/MDM_pocket_coor_shared.py", line 478, in net
    node_attr_global, pos_attr_global = self.encoder_global(
  File "~/softwares/mambaforge3/envs/pmdm/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "~/softwares/mambaforge3/envs/pmdm/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "~/softwares/PMDM/models/encoders/egnn.py", line 476, in forward
    x = layer(x, edge_index, edge_attr, batch=batch, ligand_batch=ligand_batch, size=bsize, linker_mask=linker_mask)
  File "~/softwares/mambaforge3/envs/pmdm/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "~/softwares/mambaforge3/envs/pmdm/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "~/softwares/PMDM/models/encoders/egnn.py", line 215, in forward
    hidden_out, coors_out = self.propagate(edge_index, x=feats, edge_attr=edge_attr_feats,
ValueError: too many values to unpack (expected 2)

```

**Comment by Layne-Huang** [comment]
What is the version of your pytroch_geometric? It should be 2.4.0 or older.

**Comment by wenchangzhou-qtx** [comment]
Thanks! It's running now, there is one more thing, or two things I noticed:)
1. Inside sample_frag.py, there are two lines seems overlapping (I've already commented out, but I'm not sure what I did here are actually what you meant to keep):
```
    parser.add_argument('--keep_index', nargs='+', type=int)
    parser.add_argument('-build_method', type=str, default='reconstruct',help='build or reconstruct')

#    parser.add_argument('--keep_index', nargs='+',type=int)
#    parser.add_argument('-build_method', type=str, default='build',help='build or reconstruct')

```
2. I like to generate 20 more atoms by `--num_atom 20`, but seems the program still gives `'num_atom': 10`, so here is the default value 10 (maybe) overwrites the user's input? See my output below

```
python -u sample_frag.py --ckpt data/500.pt --pdb_path receptor.pdb --mol_file SD.frag.sdf --keep_index 1 2 3 4 5 6 7 8 9 10 11 13 14 16 17 18 19 20 21 22 25 26 27 28 29 30 31 32 33 34 35 --num_atom 20 --num_samples 10 --sampling_type generalized
Entropy of n_nodes: H[N] -1.3862943649291992
[2024-04-07 21:36:04,486::test::INFO] Namespace(pdb_path='receptor.pdb', mol_file='SD.frag.sdf', num_atom=20, keep_index=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 13, 14, 16, 17, 18, 19, 20, 21, 22, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35], build_method='reconstruct', cuda=False, ckpt='data/500.pt', save_traj=False, resume=None, tag='', out_dir=None, num_samples=10, batch_size=100, clip=1000.0, seed=3047, n_steps=1000, global_start_sigma=inf, local_start_sigma=inf, w_global_pos=1.0, w_local_pos=1.0, w_global_node=1.0, w_local_node=1.0, sampling_type='generalized', eta=1.0)
[2024-04-07 21:36:04,487::test::INFO] {'model': {'type': 'diffusion', 'network': 'MDM_full_pocket_coor_shared', 'hidden_dim': 128, 'protein_hidden_dim': 128, 'num_convs': 3, 'num_convs_local': 3, 'protein_num_convs': 2, 'cutoff': 3.0, 'g_cutoff': 6.0, 'encoder_cutoff': 6.0, 'time_emb': True, 'atom_num_emb': False, 'mlp_act': 'relu', 'beta_schedule': 'sigmoid', 'beta_start': 1e-07, 'beta_end': 0.002, 'num_diffusion_timesteps': 1000, 'edge_order': 3, 'edge_encoder': 'mlp', 'smooth_conv': False, 'num_layer': 9, 'feats_dim': 5, 'soft_edge': True, 'norm_coors': True, 'm_dim': 128, 'context': 'None', 'vae_context': False, 'num_atom': 10, 'protein_feature_dim': 31}, 'train': {'seed': 2021, 'batch_size': 16, 'val_freq': 250, 'max_iters': 500, 'max_grad_norm': 10.0, 'num_workers': 4, 'anneal_power': 2.0, 'optimizer': {'type': 'adam', 'lr': 0.001, 'weight_decay': 0.0, 'beta1': 0.95, 'beta2': 0.999}, 'scheduler': {'type': 'plateau', 'factor': 0.6, 'patience': 10, 'min_lr': 1e-06}, 'transform': {'mask': {'type': 'mixed', 'min_ratio': 0.0, 'max_ratio': 1.2, 'min_num_masked': 1, 'min_num_unmasked': 0, 'p_random': 0.5, 'p_bfs': 0.25, 'p_invbfs': 0.25}, 'contrastive': {'num_real': 50, 'num_fake': 50, 'pos_real_std': 0.05, 'pos_fake_std': 2.0}}}, 'dataset': {'name': 'crossdock', 'type': 'pl', 'path': './data/crossdocked_pocket10', 'split': './data/split_by_name.pt'}}
[2024-04-07 21:36:04,487::test::INFO] Loading crossdock data...
Entropy of n_nodes: H[N] -3.543935775756836
[2024-04-07 21:36:04,487::test::INFO] Loading data...
[2024-04-07 21:36:04,557::test::INFO] Building model...
[2024-04-07 21:36:04,558::test::INFO] MDM_full_pocket_coor_shared
{'type': 'diffusion', 'network': 'MDM_full_pocket_coor_shared', 'hidden_dim': 128, 'protein_hidden_dim': 128, 'num_convs': 3, 'num_convs_local': 3, 'protein_num_convs': 2, 'cutoff': 3.0, 'g_cutoff': 6.0, 'encoder_cutoff': 6.0, 'time_emb': True, 'atom_num_emb': False, 'mlp_act': 'relu', 'beta_schedule': 'sigmoid', 'beta_start': 1e-07, 'beta_end': 0.002, 'num_diffusion_timesteps': 1000, 'edge_order': 3, 'edge_encoder': 'mlp', 'smooth_conv': False, 'num_layer': 9, 'feats_dim': 5, 'soft_edge': True, 'norm_coors': True, 'm_dim': 128, 'context': 'None', 'vae_context': False, **'num_atom': 10**, 'protein_feature_dim': 31}
sdf idr: frag_gen
Entropy of n_nodes: H[N] -1.3862943649291992
linker atom number: 31
100%|██████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 132.31it/s]
  0%|                     ~/softwares/PMDM/models/common.py:485: UserWarning: torch.sparse.SparseTensor(indices, values, shape, *, device=) is deprecated.  Please use torch.sparse_coo_tensor(indices, values, shape, dtype=, device=). (Triggered internally at ../torch/csrc/utils/tensor_new.cpp:618.)
  bgraph_adj = torch.sparse.LongTensor(

sample: 7it [00:27,  3.87s/it]
```

**Comment by Layne-Huang** [comment]
This is just the num_atom argument of the configure file, which will not affect the final 20 atom generation.
